### PR TITLE
Check if values are null. Might be the case for legacy messages

### PR DESCRIPTION
**Pull request by Wooza**

### CODE REVIEW

**Comment by Wooza** [comment]
A test build to so that affected people can verify if this fixes the bug: 
[ProspectorInfo-4.2.1-pre.zip](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/11358552/ProspectorInfo-4.2.1-pre.zip)

**Comment by Vityuri** [comment]
Good news, I can receive the shared data without a crash now! Also the shared data through chat creates a huge wall of text, it's a bit much.
2023-05-03_13-16-14_LI

**Comment by Wooza** [comment]
@Vityuri Yes, I know that this is a bit annoying, but I couldn't come up with a better approach.
The alternatives would be to exchange the prospecting data outside of the game, e.g., via file transfer and than merge the files manually, using something like https://github.com/FalcoGer/VSProspectorInfoMerger.
Another alternative would be to change this mod from client-only to server-client, but then again this would require that every server admin has to add this mod, otherwise you cannot use it. Altough I don't know If one can make the server part optional 🤔 

@p3t3rix As that fixes the initial bug I guess we can merge it

**Comment by p3t3rix** [comment]
> 

now that you mention it, a hybrid approach could work. But i think it is kind of confusing when some feature are not working/work differently when the server has something installed.
But it could open the way to some cool features like auto-syncing. I didn't play for a long time but does the world map reveal for all players (and if not is there a mod for this ?)

**Pull request merged**
